# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests on the configure branch.


image: gcc:latest

definitions:
  variables: &variables
    - name: _LEAVE_BLANK_FOR_DEFAULTS_
    - name: CI_DEV_CHECK
    - name: CI_RUN_TESTS
    - name: CI_RANKS
    - name: CI_TESTS
    - name: CI_NO_TESTS
    - name: CI_EXTRAFLAGS
    - name: CI_CONFIGURE_ARGS
  steps:
    - step: &build-test
          name: Build and Test gcc:latest
          script:
            - utils/pipeline.sh
          after-script:
            - echo "Status/Results " ;
              echo "Repo       "$BITBUCKET_REPO_FULL_NAME ; 
              echo "Branch     "$BITBUCKET_BRANCH ; 
              echo "Tag        "$BITBUCKET_TAG ; 
              echo "Commit     "$BITBUCKET_COMMIT ; 
              echo "PR         "$BITBUCKET_PR_ID ; 
              echo " " ; 
              echo "Exit code  "$BITBUCKET_EXIT_CODE

pipelines:
  default:
      - step: *build-test
  custom:
    build-test:
      - variables: *variables
      - step: *build-test
