#!/bin/bash
if [ -d ./build ]
then
    rm -rf build
fi
cmake -B build -D DIM=2 -D MPI=ON -D AMR=ON -D MMB=ON -D OPS=ON -D DEBUG=ON -D ENABLE_ALL_TESTS=ON -D VERBOSE=0
cd build
if [ $# -eq 0 ]
then
    make 
    make test
else
    make $1
fi
cd ..
