
##DEPXX=clang++
##CXX=clang++
CXX=nvcc

DIM=2
PROTO=../..

#CXXOPTFLAGS=-g 
CXXOPTFLAGS=-g -G -DTHRUST_DEBUG -DPROTO_CUDA=1
CXXOPTFLAGS+= -std=c++11 -x cu --expt-extended-lambda
CXXOPTFLAGS+= -DDIM=$(DIM) -I$(PROTO)/include -I$(PROTO)/EBProto/include 

all : ebforall.exe

ebforall.exe : EBForAll.cpp 
	$(CXX) $(CXXOPTFLAGS) EBForAll.cpp -o ebforall.exe

clean: 	
	rm -rf *.exe *.dSYM
