#!/usr/bin/python

import sys, os

if sys.argv[3] == "1":
    dir_path = os.path.dirname(os.path.realpath(__file__))
    for root, dirs, files in os.walk(os.path.join(dir_path, '../include')):
        for filename in files:
            ext = os.path.splitext(filename)[1]
            if ext == '.H':
                os.utime(os.path.join(root, filename), None)
#  else:
#      print "post-checkout: This is a file checkout. Nothing to do."
