CXX=nvcc
CXXFLAGS= -O0 -arch=compute_70

#CXXFLAGS+= -std=c++14 -DDIM=2 -lnvToolsExt #-DPROTO_HIP #--expt-extended-lambda
CXXFLAGS+=-g -std=c++14 -DPROTO_CUDA -DDIM=3 -x cu --expt-extended-lambda -lnvToolsExt #-DPROTO_HIP #--expt-extended-lambda
#CXXFLAGS+= -DsuperDebug

INCL+= -I../include/ -I./src/

SRCS := $(wildcard *.cpp) 
OBJS=$(SRCS:.cpp=)
all: $(OBJS)

$(OBJS): %: %.cpp
	$(CXX) $(CXXFLAGS) $(INCL) $(LIBS) $< -o $@.exe


clean:
	rm -rf *.exe *.o
