#ifndef __DEBUGHOOKS__
#define __DEBUGHOOKS__

#include "Proto_WriteBoxData.H"
using Proto::BoxData;

void printData1(BoxData<double, 1>* dataPtr);
void printDataDim(BoxData<double, DIM>* dataPtr);
void printColumn1(BoxData<double, 1>* dataPtr, int column);
void printColumnDim(BoxData<double, DIM>* dataPtr, int column);
void writeData1(BoxData<double, 1>* dataPtr);
void maxMinData1(BoxData<double, 1>* dataPtr);
void maxMinDataDim(BoxData<double, DIM>* dataPtr);
void  viewData1(BoxData<double, 1>* dataPtr);
void writeDataDim(BoxData<double, DIM>* dataPtr);
void  viewDataDim(BoxData<double, DIM>* dataPtr);
void ProtoFunctionToGetStuffIntoTheSymbolTable();

             
             

#include "implem/Proto_DebugHooksImplem.H"
#endif
