#ifndef __PROTO_AMR_HEADER__
#define __PROTO_AMR_HEADER__

#define PR_AMR

#include "Proto.H"

#include "amr/Proto_FinitePointSet.H"
#include "amr/Proto_AMRGrid.H"
#include "amr/Proto_AMRData.H"
#include "amr/Proto_LevelFluxRegister.H"
#include "amr/Proto_BoxOp.H"
#include "amr/Proto_LevelOp.H"
#include "amr/Proto_AMROp.H"
#include "amr/Proto_LevelSolver.H"
#include "amr/Proto_AMRSolver.H"

#endif
