#!/bin/bash 
#SBATCH --qos=debug
#SBATCH --time=10
#SBATCH --nodes=1
#SBATCH --tasks-per-node=32
#SBATCH --constraint=haswell
#SBATCH -J runTest
#SBATCH -o runTest.%j.out
#SBATCH -e runTest.%j.err

export PR_TIMER=1
srun --export=PR_TIMER ./runTest.exe 10
